name: fresheval
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.1.0
  camera: ^0.11.0+2
  http: ^0.13.5  # For making HTTP requests
  image_picker: ^0.8.7+4
  permission_handler: ^11.3.1  # Use the latest stable version
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.11.0
  image: ^3.2.0
  path_provider: ^2.0.12
  flutter_vision: ^1.1.4
  intl: ^0.19.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/efficientnetb7_fixed.tflite
    - assets/efficientnetb7_label.txt
    - assets/yolov8_best.tflite
    - assets/best_float16.tflite
    - assets/yolov8_label.txt
    - assets/null.tflite
    - assets/null_label.txt
    - assets/img/Marasigan.jpg
    - assets/img/Agbayani.jpg
    - assets/img/Belen.jpg
    - assets/img/Limson.jpg
    - assets/img/clean_cam.png
    - assets/img/good_lighting.png
    - assets/img/steady_clear.png
    - assets/img/full_view.png
    - assets/img/logo.png
    - assets/img/logo2.png


